{
    'name': 'Tournament System',
    'version': '17.0.1.0.0',
    'category': 'Tools',
    'summary': 'Tournament System',
    'description': 'This module allows you to manage tournaments and matches for a sports event.',
    'author': 'leonardo02lobo',
    'depends': ['base', 'mail', 'contacts', 'sale_management', 'account'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'wizard/tournament_canceld_wizard_views.xml',
        'views/tournament_views.xml',
        'views/event_tournament_views.xml',
        'views/event_tournament_category_views.xml',
        'views/event_tournament_registration_views.xml',
        'views/event_tournament_score_views.xml',
        'report/tournament_report_action.xml',
        'report/tournament_layout.xml',
        'report/tournament_report_template.xml',
        'report/tournament_category_report_template.xml',
        'report/tournament_participant_report_template.xml',
        'report/tournament_score_report_template.xml',
        'report/report_invoice_inherit.xml',
    ],
    'assets': {
        'web.report_assets_common': [
            'tournament_system/static/src/css/tournament_report.css',
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'images': ['static/description/icon.png'],
}